services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airflow_db
      MYSQL_USER: airflow
      MYSQL_PASSWORD: airflow
    volumes:
      - mysql_data:/var/lib/mysql

  airflow:
    # build: .
    image: apache/airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+pymysql://airflow:airflow@mysql:3306/airflow_db
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    command: >
      bash -c "airflow db upgrade &&
               airflow users create --username admin --password admin --firstname a --lastname b --role Admin --email admin@example.com &&
               airflow webserver"
    volumes:
      - .airflow/dags:/var/lib/dags

volumes:
  mysql_data:
